parameters:
    acme_connector.job_name.custom_csv_product_import: 'custom_csv_product_import'

services:
    acme_connector.job.custom_csv_product_import:
        class: 'Acme\Bundle\CsvConnectorBundle\Job\Job'
        arguments:
            - '%acme_connector.job_name.custom_csv_product_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@acme_connector.step.custom_csv_product_import.import'
                - '@pim_connector.step.csv_product.import_associations'
        tags:
            - { name: akeneo_batch.job, connector: 'Custom Connector', type: '%pim_connector.job.import_type%' }

    acme_connector.job.job_parameters.custom_csv_product_import:
        class: 'Acme\Bundle\CsvConnectorBundle\JobParameters\CustomCsvProductImport'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_import'
            - '@pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_import'
            - ['%acme_connector.job_name.custom_csv_product_import%']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    acme_connector.job.job_parameters.provider.custom_csv_product_import:
        class: 'Pim\Bundle\EnrichBundle\Provider\Form\JobInstanceFormProvider'
        arguments:
            -
              custom_csv_product_import: pim-job-instance-custom-csv-product-import
        tags:
            - { name: pim_enrich.provider.form }

    acme_connector.step.custom_csv_product_import.import:
        class: 'Acme\Bundle\CsvConnectorBundle\Step\ItemStep'
        arguments:
          - 'import'
          - '@event_dispatcher'
          - '@akeneo_batch.job_repository'
          - '@acme_connector.reader.file.custom_csv_product'
          - '@pim_connector.processor.denormalization.product'
          - '@pim_connector.writer.database.product'
          - '%pim_job_product_batch_size%'

    acme_connector.reader.file.custom_csv_product:
        class: 'Acme\Bundle\CsvConnectorBundle\Reader\CustomProductReader'
        arguments:
            - '@pim_connector.reader.file.csv_iterator_factory'
            - '@acme_connector.array_converter.flat_to_standard.product_delocalized'
            - '@pim_connector.reader.file.media_path_transformer'
            - []

    acme_connector.array_converter.flat_to_standard.product_delocalized:
        class: 'Acme\Bundle\CsvConnectorBundle\ArrayConverter\FlatToStandard\EntityWithValuesDelocalized'
        arguments:
            - '@acme_connector.array_converter.flat_to_standard.product'
            - '@pim_catalog.localization.localizer.converter'

    acme_connector.array_converter.flat_to_standard.product:
        class: 'Acme\Bundle\CsvConnectorBundle\ArrayConverter\FlatToStandard\Product'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.field_converter'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_merger'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_mapper'
            - '@acme_connector.array_convertor.checker.fields_requirement'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.array_converter.flat_to_standard.product_value'

    acme_connector.array_convertor.checker.fields_requirement:
        class: 'Acme\Bundle\CsvConnectorBundle\ArrayConverter\FlatToStandard\FieldsRequirementChecker'
